# Generated by Django 6.0.5 on 2026-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeraConsultaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('motivo', models.TextField(blank=True)),
                ('desde_cuando', models.TextField(blank=True)),
                ('manifestacion', models.TextField(blank=True)),
                ('expectativa', models.TextField(blank=True)),
                ('modalidad', models.CharField(blank=True, max_length=80)),
                ('disponibilidad', models.TextField(blank=True)),
                ('resumen_generado', models.TextField(blank=True)),
                ('profesional_destino', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(default='nuevo', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
