# Generated by Django 6.0.5 on 2026-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeraconsultalead',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='primeraconsultalead',
            name='profesional_asignado',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='primeraconsultalead',
            name='estado',
            field=models.CharField(default='pendiente', max_length=40),
        ),
    ]
