# Generated by Django 6.0.5 on 2026-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_primeraconsultalead_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeraconsultalead',
            name='contacto',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
